### ISSUE TITLE
the plugin doesn't work for me, gerrit 2.11.3, redmine 3.3.0.stable

### ISSUE THREAD

**Issue by sherry721** [tru/redmine-gerrit-scripts#7]
When I execute a git commit command with the id of an issue ( #900 ) , nothing happened in Redmine. and I got in error_log the message : (Gerrit installed in Windows 2008, Redmine installed in Ubuntu 14.04)

ERROR com.google.gerrit.common.ChangeHookRunner : Error running hook C:\Bitnami\redmine-3.0.3-0\gerrit\review_site\hooks\patchset-created.py
java.io.IOException: Cannot run program "C:\Bitnami\redmine-3.0.3-0\gerrit\review_site\hooks\patchset-created.py" (in directory "D:\SourceCode\Projects\MP1234\alps\abi.git"): CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessBuilder.start(Unknown Source)
	at com.google.gerrit.common.ChangeHookRunner$HookTask.runHook(ChangeHookRunner.java:892)
	at com.google.gerrit.common.ChangeHookRunner$AsyncHookTask.run(ChangeHookRunner.java:988)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:379)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 11 more
-- 
Best regards, Sherry

**Comment by tru** [comment]
These scripts are no longer maintained. So any change would have to be done by you.
